Feature/ig 3 4
Djkill1994/instagram-jedi-app pull request #11
Opened 2022-09-04 14:01 UTC by Djkill1994

Реализована адаптивность чата , переработаны стили проекта , переделана адаптивность в проекте , устранены баги

2022-09-04 14:35 UTC, Candyn requested changes

2022-09-04 14:35 UTC, Candyn commented on src/common/components/BarInstallApps/BarInstallApps.module.scss
> +.imgWrapper {
зачем тебе вложенный селектор по тэгу img, если у тебя уже есть класс?

2022-09-04 14:35 UTC, Candyn commented on src/common/components/BarInstallApps/BarInstallApps.tsx
> +        className={styles.imgWrapper}
этот класс уже лучше накинуть сразу на img

2022-09-04 14:35 UTC, Candyn commented on src/common/components/BarInstallApps/BarInstallApps.tsx
> +        className={styles.imgWrapper}
и чтобы не дублировать код, можешь вынести данные в константу выше компанента:
`const APPS = [{ href: '', alt: '' }]`
`{APPS.map(({href, alt}) => <Link><img /></Link>}`

2022-09-04 14:35 UTC, Candyn commented on src/common/components/EmojiBar/EmojiBar.tsx
> +import Button from "@mui/material/Button";
import { Button } from "@mui/material";

2022-09-04 14:35 UTC, Candyn commented on src/common/components/Footer/Footer.module.scss
> +  margin-top: 40px;
старайся делать так, чтобы у тебя не было внешних оступов во вне от компонента

2022-09-04 14:35 UTC, Candyn commented on src/common/components/Header/NavigationBarHeader/NavigationBarHeader.module.scss
> +  button{
тот же момент, не делай так, сделай просто класс и его уже накинь на кнопку

2022-09-04 14:35 UTC, Candyn commented on src/common/components/EmojiBar/EmojiBar.tsx
> +import Button from "@mui/material/Button";
и в других местах фиксани импорты

2022-09-04 14:35 UTC, Candyn commented on src/features/Login/components/LogInForm/CustomForm/CustomForm.tsx
> +            fullWidth={true}
лучше верни как было, просто fullWidth (это и будет true)

2022-09-04 14:35 UTC, Candyn commented on src/features/Login/components/LogInForm/CustomForm/CustomForm.tsx
> +        <Grid item sm={12} width="100%">
width="100%" - тут точно он нужен?

2022-09-04 14:35 UTC, Candyn commented on src/features/Login/components/Login.module.scss
> +//@media (min-width: 350px) {
?

2022-09-04 14:35 UTC, Candyn commented on src/features/Login/components/WindowLoginForm/WindowLoginForm.module.scss
> +.logo{
.logo {

2022-09-04 14:35 UTC, Candyn commented on src/features/Messages/components/ChatBar/ChatBar.module.scss
> +  width: 48vw;
плохая затея с vw, придумай что-нибудь другое

2022-09-04 14:35 UTC, Candyn commented on src/features/Messages/components/ChatBar/ChatBar.module.scss
> +@media (max-width: 900px) {
плохая затея с media)

2022-09-04 14:35 UTC, Candyn commented on src/features/Messages/components/ChatSection/InputBar/InputBar.tsx
> +          padding="o 10px"
o?)))

2022-09-04 14:35 UTC, Candyn commented on src/features/Messages/components/ChatSection/InputBar/InputBar.tsx
> +            <Button type="submit" variant="text" disableTouchRipple={true}>
<Button type="submit" variant="text" disableTouchRipple>

2022-09-04 14:35 UTC, Candyn commented on src/features/Messages/components/Messages.module.scss
> +  width: 75vw;
плохая затея с vw, и с медиа

2022-09-04 14:35 UTC, Candyn commented on src/features/Messages/components/UserBarMessages/UserBarMessages.module.scss
> +  width: 27vw;
27vw - плохой подход

2022-09-04 14:35 UTC, Candyn commented on src/features/Post/components/Post/CommentsPost/CommentsPost.tsx
> +      <Button disableTouchRipple={true} variant="text">
<Button disableTouchRipple variant="text">

2022-09-04 14:35 UTC, Candyn commented on src/features/Post/components/Post/Post.module.scss
> +  width: 50vw;
плохой подход

2022-09-04 14:35 UTC, Candyn commented on src/features/Post/components/Post/Post.module.scss
> +@media (max-width: 700px) {
плохой подход

2022-09-04 14:35 UTC, Candyn commented on src/features/Post/components/PostsContainer/PostsContainer.tsx
> +      {/*<Navbar />*/}
sos

2022-09-04 14:35 UTC, Candyn commented on src/features/Registration/components/RegistrationCustomForm/RegistrationCustomForm.tsx
> +      width="100%"
точно нужен?

2022-09-04 14:42 UTC, Djkill1994 commented on src/common/components/BarInstallApps/BarInstallApps.module.scss
> +.imgWrapper {
Потому что в этом классе несколько img тегов и я применю к нескольким , если сделаю просто img без вложения то тогда будут применятся стили ко всем img проекта

2022-09-04 15:02 UTC, Djkill1994 commented on src/features/Login/components/LogInForm/CustomForm/CustomForm.tsx
> +        <Grid item sm={12} width="100%">
Нужен , что бы блок занимал всю ширину

2022-09-06 18:49 UTC, Candyn requested changes

2022-09-06 18:49 UTC, Candyn commented on src/common/components/BarInstallApps/BarInstallApps.tsx
> +  const APPS = [
вынеси за комопнент

2022-09-06 18:49 UTC, Candyn commented on src/features/Registration/components/RegistrationCustomForm/RegistrationCustomForm.tsx
> +import Grid from "@mui/material/Grid";
поправь и тут импорты

2022-09-10 10:58 UTC, Candyn approved these changes

2022-09-14 17:27 UTC, merged