IG-9 "Реализация страницы Login и Registration"
Djkill1994/instagram-jedi-app pull request #3
Opened 2022-03-22 22:55 UTC by Djkill1994

IG-9 "Реализация страницы Login и Registration. Реализована адаптивная вёрстка , реализована анимация на стартовой странице"
![Screen1](https://user-images.githubusercontent.com/84898137/159589574-0dc1ccb8-dad3-44e7-a786-d2f162df036c.png)
![Screen2](https://user-images.githubusercontent.com/84898137/159589621-9614f640-ac8c-42b5-98f8-e27738137f9b.png)

2022-03-24 08:07 UTC, Candyn requested changes

2022-03-24 08:07 UTC, Candyn commented on src/common/components/App/App.tsx
> +      {/*<div className={s.appBody}>*/}
удали

2022-03-24 08:07 UTC, Candyn commented on src/common/components/App/App.module.scss
>  .appWrapperContent {
удали неиспользуемые классы

2022-03-24 08:07 UTC, Candyn commented on src/common/components/Login/Login.module.scss
> +  //margin-top: 15px;
удали везде закоменченый код

2022-03-24 08:07 UTC, Candyn commented on package.json
> +    "react-spring": "^9.4.4",
удали

2022-03-24 08:07 UTC, Candyn commented on src/common/components/Login/Footer/Footer.tsx
> +          <div className={s.sectionOne}>
обсудить тут верстку

2022-03-27 15:59 UTC, Candyn requested changes

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/WindowLoginForm/WindowLoginForm.tsx
> +                width: "254px",
?

2022-03-27 15:59 UTC, Candyn commented on src/common/components/App/App.tsx
export cont ROUTE_PATHS = {
  Login: '/',
 SignUp: 'signUp'
}

2022-03-27 15:59 UTC, Candyn commented on src/common/components/ContentWrapper/ContentWrapper.tsx
> +export const ContentWrapper: React.FC = () => {
export const ContentWrapper: React.FC = ({ children }) => {

2022-03-27 15:59 UTC, Candyn commented on src/common/components/ContentWrapper/ContentWrapper.tsx
> +        <PostsContainer />
{children}

2022-03-27 15:59 UTC, Candyn commented on src/common/components/App/App.tsx
> +        <Route path="/content" element={<ContentWrapper />} />
<ContentWrapper>
  <Switch>
    <Route path="/content" element={PostContent} />
  </Switch>
</ContentWrapper>

2022-03-27 15:59 UTC, Candyn commented on src/common/components/DecorationBorder/DecorationBorder.module.scss
> +  .one, .two {
.line

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Footer/Footer.tsx
> +const ComponentLink: React.FC<ComponentLinkPropsType> = ({ url, title }) => {
вынеси в компонент

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Header/Header.tsx
> +  console.log("Header Load");
?

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/LogInForm/LogInForm.tsx
> +    console.log({
?

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/LogInForm/LogInForm.tsx
> +    <div>
замени на <></>

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/LogInForm/LogInForm.tsx
> +        <div className={s.sendBtnWrapper}>
почисти тут дивы

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/Login.tsx
> +export const Login: React.FC = () => {
перени в фича папку

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/WindowAnimatedPhone/InfinitySlider/InfinitySlider.tsx
> +    setInterval(() => {
const interval = setInterval(
и ниже
return () => clearInterval(interval);

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/WindowLoginForm/WindowLoginForm.module.scss
> +.barInstallApps, .registrationBarWrapper,
почитсить

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Login/WindowLoginForm/WindowLoginForm.tsx
> +    <div className={s.loginFormWrapper}>
используй стэки / гриды

2022-03-27 15:59 UTC, Candyn commented on src/common/components/PasswordReset/PasswordReset.tsx
> +    console.log({
?

2022-03-27 15:59 UTC, Candyn commented on src/common/components/PasswordReset/PasswordReset.tsx
> +          <DecorationBorder />
<DecorationBorder className={s.decorationBorder} />

а в компонете делаешь опциональный пропс className?: string;
и делаешь склейку классов на верхнем уровне: 
return (<div className={clxs(localClass, prop.className)}>13123</div>)

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Registration/Registration.tsx
> +export const Registration: React.FC = () => {
вынеси в фичу

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Registration/Registration.tsx
> +    console.log({
?

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Registration/Registration.tsx
> +interface StateProps {
укажи что это за стейт к примеру RegistationFormState

2022-03-27 15:59 UTC, Candyn commented on src/common/components/Registration/Registration.tsx
> +    <div>
<>

2022-03-27 15:59 UTC, Candyn commented on src/features/post/components/PostsContainer/PostsContainer.tsx
> +  console.log("Posts Load");
?

2022-03-28 10:20 UTC, Djkill1994 commented on src/common/components/App/App.tsx
done

2022-03-28 12:12 UTC, Djkill1994 commented on src/common/components/Footer/Footer.tsx
> +const ComponentLink: React.FC<ComponentLinkPropsType> = ({ url, title }) => {
done

2022-03-28 12:12 UTC, Djkill1994 commented on src/common/components/Header/Header.tsx
> +  console.log("Header Load");
done

2022-03-28 12:13 UTC, Djkill1994 commented on src/common/components/PasswordReset/PasswordReset.tsx
> +    console.log({
done

2022-03-28 12:13 UTC, Djkill1994 commented on src/common/components/Registration/Registration.tsx
> +export const Registration: React.FC = () => {
done

2022-03-28 12:18 UTC, Djkill1994 commented on src/common/components/DecorationBorder/DecorationBorder.module.scss
> +  .one, .two {
done

2022-03-28 12:22 UTC, Djkill1994 commented on src/common/components/Login/Login.tsx
> +export const Login: React.FC = () => {
done

2022-03-28 12:22 UTC, Djkill1994 commented on src/common/components/Registration/Registration.tsx
> +interface StateProps {
done

2022-03-29 00:18 UTC, Djkill1994 commented on src/common/components/Login/WindowLoginForm/WindowLoginForm.tsx
> +                width: "254px",
done

2022-03-29 00:19 UTC, Djkill1994 commented on src/common/components/Login/LogInForm/LogInForm.tsx
> +    <div>
done

2022-03-29 00:19 UTC, Djkill1994 commented on src/common/components/Login/LogInForm/LogInForm.tsx
> +        <div className={s.sendBtnWrapper}>
done

2022-03-29 00:20 UTC, Djkill1994 commented on src/common/components/Login/WindowLoginForm/WindowLoginForm.module.scss
> +.barInstallApps, .registrationBarWrapper,
done

2022-03-29 00:20 UTC, Djkill1994 commented on src/common/components/Login/WindowLoginForm/WindowLoginForm.tsx
> +    <div className={s.loginFormWrapper}>
done

2022-03-29 00:20 UTC, Djkill1994 commented on src/common/components/PasswordReset/PasswordReset.tsx
> +          <DecorationBorder />
done

2022-03-29 00:20 UTC, Djkill1994 commented on src/common/components/Registration/Registration.tsx
> +    console.log({
done

2022-03-29 00:21 UTC, Djkill1994 commented on src/common/components/Registration/Registration.tsx
> +    <div>
done

2022-03-29 00:21 UTC, Djkill1994 commented on src/features/post/components/PostsContainer/PostsContainer.tsx
> +  console.log("Posts Load");
done

2022-03-29 00:37 UTC, Djkill1994 commented on src/common/components/Login/WindowAnimatedPhone/InfinitySlider/InfinitySlider.tsx
> +    setInterval(() => {
done

2022-03-29 00:42 UTC, Djkill1994 commented on src/common/components/ContentWrapper/ContentWrapper.tsx
> +export const ContentWrapper: React.FC = () => {
done

2022-03-29 00:42 UTC, Djkill1994 commented on src/common/components/ContentWrapper/ContentWrapper.tsx
> +        <PostsContainer />
done

2022-03-29 00:42 UTC, Djkill1994 commented on src/common/components/App/App.tsx
> +        <Route path="/content" element={<ContentWrapper />} />
done

2022-03-29 08:03 UTC, Candyn requested changes

2022-03-29 08:03 UTC, Candyn commented on src/common/components/Footer/Footer.module.scss
> +.barTwo {
useless class

2022-03-29 08:03 UTC, Candyn commented on src/common/components/DecorationBorder/DecorationBorder.module.scss
> +  display: flex;
stack

2022-03-29 08:03 UTC, Candyn commented on src/common/components/ContentWrapper/ContentWrapper.module.scss
> +  display: flex;
stack

2022-03-29 08:03 UTC, Candyn commented on src/common/components/BarInstallApps/BarInstallApps.module.scss
> +  flex-direction: column;
stack

2022-03-29 08:03 UTC, Candyn commented on src/features/Login/LogInForm/CustomForm/CustomForm.module.scss
> +  display: flex !important;
important? stack?

2022-03-29 08:03 UTC, Candyn commented on src/features/Login/LogInForm/CustomForm/CustomForm.tsx
> +    console.log({
?

2022-03-29 08:03 UTC, Candyn commented on src/features/Login/LogInForm/LogInForm.module.scss
> +  font-size: 14px;
stack

2022-03-29 08:03 UTC, Candyn commented on src/features/Login/Login.module.scss
> +  display: flex;
stack

2022-03-29 08:03 UTC, Candyn commented on src/features/Login/Login.tsx
> +  console.log("Login Load");
?

2022-03-29 08:03 UTC, Candyn commented on src/features/Login/WindowLoginForm/WindowLoginForm.module.scss
> +  display: flex;
stack

2022-03-29 08:03 UTC, Candyn commented on src/features/Login/WindowLoginForm/WindowLoginForm.tsx
> +    <div className={s.loginFormWrapper}>
перепиши на stack

2022-03-29 08:03 UTC, Candyn commented on src/features/Registration/RegistrationCustomForm/RegistrationCustomForm.tsx
> +    console.log({
?

2022-03-29 11:55 UTC, Candyn requested changes

2022-03-29 11:55 UTC, Candyn commented on src/common/components/App/App.module.scss
> +.allPageWrapper {
этот класс нужен?

2022-03-29 11:55 UTC, Candyn commented on src/common/components/App/App.module.scss
> +  flex-direction: column;
stack

2022-03-29 11:55 UTC, Candyn commented on src/common/components/DecorationBorder/DecorationBorder.tsx
> +      <span>OR</span>
еще можно использовтаь для текста копмонент Typography

2022-03-29 11:55 UTC, Candyn commented on src/common/components/Footer/ComponentLink/ComponentLink.tsx
> +interface ComponentLinkPropsType {
ComponentLinkProps

2022-03-29 11:55 UTC, Candyn commented on src/features/Login/components/LogInForm/LogInForm.tsx
> +    <>
можно тут сделать еще stack со spacing, и удалить класс .stack

2022-03-29 11:55 UTC, Candyn commented on src/features/Login/components/LogInForm/LogInForm.tsx
> +        <div className={s.errorWindow}>ERROR</div>
Typography

2022-03-29 11:55 UTC, Candyn commented on src/features/Login/components/WindowAnimatedPhone/WindowAnimatedPhone.module.scss
> +  display: flex;
stack

2022-03-29 11:55 UTC, Candyn commented on src/features/Registration/components/AgreementPolicy/AgreementPolicy.tsx
> +      <p>
stack

2022-03-29 11:55 UTC, Candyn commented on src/features/Registration/components/AgreementPolicy/AgreementPolicy.module.scss
> +    display: flex;
stack

2022-03-29 11:55 UTC, Candyn commented on src/features/Registration/components/Registration.tsx
> +          Sign up to see photos and videos from your friends.
Typography

2022-03-29 11:55 UTC, Candyn commented on src/features/Registration/components/Registration.tsx
> +        <span>Have an account?</span>
Typography

2022-03-29 11:55 UTC, Candyn commented on src/features/Registration/components/Registration.tsx
> +            Log in with Facebook
Typography

2022-03-29 11:55 UTC, Candyn commented on src/features/Registration/components/AgreementPolicy/AgreementPolicy.tsx
> +          Cookies Policy
Typography

2022-03-29 13:21 UTC, Candyn approved these changes

2022-03-29 13:23 UTC, merged