Feature/ig 3 2 Implementation of logic chat message bar
Djkill1994/instagram-jedi-app pull request #9
Opened 2022-07-24 15:18 UTC by Djkill1994

Реализовано : Запрос на сервер за пользователями в модальном окне 
                        Отправка данных выбранного пользователя и присвоения ему roomId
                        Реализован чат сервер с локальной базой данных lowDb для хранения сообщений
                        Реализован хук useChat
                        Реализовано подключение к webSocket
                       
<img width="523" alt="Screenshot_1" src="https://user-images.githubusercontent.com/84898137/180653856-5f44fea0-fa79-43ac-8d3a-75f2aa92014f.png">
<img width="960" alt="Screenshot_2" src="https://user-images.githubusercontent.com/84898137/180653878-82ea5a2e-b2fe-483d-b5eb-b93e4833c700.png">
<img width="959" alt="Screenshot_3" src="https://user-images.githubusercontent.com/84898137/180653882-4c366609-68b5-4351-b0e9-9d2d132bc03c.png">

2022-07-28 19:20 UTC, Candyn requested changes

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.module.scss
> +}
ты изаешь scss и спомощью его можно вытворять такие штуки:

```
.userMessageItem {
   padding: 8px 20px;
   
   &:active {
       background-color: #dbdbdb;
   }
 }
```
поправь плз и в других местах

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +import s from "./UserItem.module.scss";
забыл переименовать s на styles?

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +  onClick: (user: IUser | any) => void;
`IUser | any`??? а можно без any?

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +  sizeAvatar: any;
any

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +  sizeAvatar: any;
поправь все остальные места

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +  sizeAvatar: any;
avatartSize, по поводу типа

type AvatarSize = 'small' | 'large' | 'big'

avatartSize: AvatarSize;

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +  if (sizeAvatar === "small") {
используй обект:

только вынеси эту константу за компонент (выше его)

```
const AVATAR_SIZES = {
   small: { width: 24, height: 24 }
}
```

и потом в коде:

`sx={AVATAR_SIZES[avatarSize]}`

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +        isSelected === true
`=== true` - просто `isSelected ? xxx : xxx`

2022-07-28 19:20 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +      className={
`className={clsx(s.userMessageItem, что-то еще, {[s.active]: isSelected})}`, логика `user.id === activeChatUser?.id `- выносится за компонент в проп, `isSelected={user.id === activeChatUser?.id}`

2022-07-28 19:20 UTC, Candyn commented on src/common/hooks/useModal.ts
> +export const useModal = () => {
про типы забыли?

2022-07-28 19:20 UTC, Candyn commented on src/features/Login/components/LogInForm/CustomForm/CustomForm.tsx
> +      dispatch(setUserData(data));
засунь эту логику в `useEffect` выше

2022-07-28 19:20 UTC, Candyn commented on src/features/Login/components/LogInForm/CustomForm/CustomForm.tsx
> +      dispatch(setUserData(data));
мб можно удалить `setAuth(true) ` и вместо этого создать экшен типа `setAuthUser()` - и будет храниться залогированный юзер

2022-07-28 19:20 UTC, Candyn commented on src/features/Login/slices/login.slice.ts
> +  userName: string;
а тут просто храни обьект `authUser?: IUser`

2022-07-28 19:20 UTC, Candyn commented on src/features/Login/slices/login.slice.ts
> +      state.userName = payload.userName;
`state.authUser = payload`

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/api/activeUser.api.ts
> +export const activeUserApi = createApi({
`activeChatUserApi`

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/api/activeUser.api.ts
> +        activeUserId: any;
any?, и зачем ты еще туда передаешь userName, userAvatar

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/api/users.api.ts
> +export const usersApi = createApi({
перенеси это в User фичи

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/ChatBar/InputBar/InputBar.tsx
> +  const handleChangeText = (e: any) => {
any

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/ChatBar/InputBar/InputBar.tsx
> +  const handleChangeText = (e: any) => {
также поправь везде `any`

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/ChatBar/InputBar/InputBar.tsx
> +          {inputStr !== "" ? (
```
{inputStr ? <button type="submit" className={s.sendBtn}>
               Send
             </button> : <label htmlFor="icon-button-file">
```

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.module.scss
> +  margin: 10px 145px !important;
можно без important?

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.tsx
> +export const AllUsersWindowModal = () => {
`export const AllUsersWindowModal = (): VFC`

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.tsx
> +        onClose={() => close()}
onClose={close}

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.tsx
> +                  }).then(() => close())
`  }).then(close)`

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.tsx
> +      <button onClick={() => open()}>
тоже самое

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.tsx
> +      <button onClick={() => open()}>
мб юзать кнопку с mui?

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/UserBarMessages.tsx
> +// fix s to styles on all places in the project
харош)

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/slices/message.slice.ts
> +export const MessageSelector = (state: RootState) => state.activeUserChat;
с маленькой буквы

2022-07-28 19:20 UTC, Candyn commented on src/features/Messages/slices/message.slice.ts
> +export const MessageSelector = (state: RootState) => state.activeUserChat;
мб переименовать на activeChatUserSelector и также название фичи/слайса

2022-07-28 19:20 UTC, Candyn commented on src/features/Post/slices/post.slise.ts
> +  id: number | null;
почему null везде?

2022-08-07 17:23 UTC, Candyn requested changes

2022-08-07 17:23 UTC, Candyn commented on src/common/components/UserItem/UserItem.module.scss
> +  cursor: pointer;
а почему только на ховер? почему не юзаешь scss?) (вынеси просто на 3 строчку этот код)

2022-08-07 17:23 UTC, Candyn commented on src/common/components/UserItem/UserItem.module.scss
> +  cursor: pointer;
тоже самое

2022-08-07 17:23 UTC, Candyn commented on src/common/components/UserItem/UserItem.module.scss
> +  margin-left: 15px!important;
без импортента никак?

2022-08-07 17:23 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +type avatarSize = "small" | "large" | "big";
AvatarSizes

2022-08-07 17:23 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +  avatarSize: avatarSize;
можно сделать не обязательным пропсом и на 25 строчке присвоить значение по дефолту (avatarSize = 'small',)

2022-08-07 17:23 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +  onClick: VoidFunction;
я бы тоже сделал не обязательным пропсом

2022-08-07 17:23 UTC, Candyn commented on src/common/components/UserItem/UserItem.tsx
> +      <Stack direction="column">
почему тут стэк? тут же всего 1 жочерний элемент (возможно его можно просто удалить)

2022-08-07 17:23 UTC, Candyn commented on src/common/hooks/useModal.ts
> +interface IProps {
почему назвал IProps? тем более, что в хуки ты присвоил этот тип возвращаемому значению, что не логично, если считать, что пропсы это аргументы функции (назови IUseModalReturn, к примеру)

2022-08-07 17:23 UTC, Candyn commented on src/features/Messages/component/ChatBar/InputBar/InputBar.module.scss
> +    cursor: pointer;
похожая ситуация, не за чем деалть курсор поинтер только на ховер, сделай его по дефолту таким всегда

2022-08-07 17:23 UTC, Candyn commented on src/features/Messages/component/ChatBar/InputBar/InputBar.tsx
> +  sendMessage: (arg1: string) => void;
arg1 - крайне плохое название для аргумента

2022-08-07 17:23 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.tsx
> +export const AllUsersWindowModal: VFC = () => {
Window - лишнее слово здесь, может назвать этот комопнет SearchUsersModal?

2022-08-07 17:23 UTC, Candyn commented on src/features/Messages/component/UserBarMessages/AllUsersWindowModal/AllUsersWindowModal.tsx
> +      <Button onClick={open}>
можешь это не исправлять, но на будущее, ты называешь этот компонент модалкой, но по факту тут есть еще кнопка

2022-08-07 17:23 UTC, Candyn commented on src/features/Messages/slices/message.slice.ts
> +  activeUserId: any;
any!!

2022-08-07 17:23 UTC, Candyn commented on src/features/Messages/slices/message.slice.ts
> +export const MessageSelector = (state: RootState) => state.activeUserChat;
забыл исправить?

2022-08-07 17:23 UTC, Candyn commented on src/features/Messages/slices/message.slice.ts
> +interface IMessageSlice {
а это куда? заменить MessageState?

2022-08-07 17:23 UTC, Candyn commented on src/features/Post/components/Post/CommentsPost/CommentsPost.tsx
> +  const onEmojiClick = (event: React.MouseEvent, emojiObject: IEmojiData) => {
видел  уже эту логику (мб вынести в отдельный компонент всю эту логику с компонентом эмоджи?) сделай это в отдельной задаче

2022-08-07 17:23 UTC, Candyn commented on src/features/Post/slices/post.slise.ts
> +// type contentType = {
закоменченный код?

2022-08-07 17:23 UTC, Candyn commented on src/features/Registration/components/Registration.module.scss
> +      cursor: pointer;
исправь

2022-08-07 17:23 UTC, Candyn commented on src/mocks/data/selectedUsersChat.ts
> +export interface activeChatUsers {
IActiveChatUsers

2022-08-07 17:23 UTC, Candyn commented on src/mocks/data/selectedUsersChat.ts
> +  activeUserId: number | string;
почему string | number ?

2022-08-07 17:23 UTC, Candyn commented on src/mocks/data/selectedUsersChat.ts
> +  activeUserId: number | string;
сделай просто string

2022-08-07 17:23 UTC, Candyn commented on src/mocks/data/selectedUsersChat.ts
> +  roomId: number | string;
тоже самое

2022-08-07 18:09 UTC, Djkill1994 commented on src/features/Messages/slices/message.slice.ts
> +  activeUserId: any;
я не знаю какой ты коммит смотришь , но это я давно пофиксил

2022-08-07 18:44 UTC, Candyn approved these changes

2022-08-07 18:52 UTC, merged